# Generated by Django 5.1.1 on 2025-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('people', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('contacted', models.BooleanField(default=False)),
                ('reservation', models.CharField(default='Confirmed', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contact_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('enquiry', models.CharField(default='Anything Else', max_length=30)),
                ('message', models.TextField()),
                ('contacted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='event_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('people', models.PositiveIntegerField()),
                ('eventname', models.CharField(default='Other', max_length=50)),
                ('message', models.TextField()),
                ('contacted', models.BooleanField(default=False)),
                ('reservation', models.CharField(default='Confirmed', max_length=100)),
            ],
        ),
    ]
