# Generated by Django 5.1.1 on 2025-01-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_table',
            name='enquiry',
            field=models.CharField(max_length=30),
        ),
    ]
