# Generated by Django 5.1.1 on 2025-01-07 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_contact_table_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_table',
            name='submitdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='contact_table',
            name='submitdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event_table',
            name='submitdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
